### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 74

### ISSUE THREAD

**Issue by JeromeSaby** [staticsafe/twitter-advertiser-list-converter#2]
I modified the script in order to make it work for me : 

I replaced (line 47) : 

finaluserslist.write("\n".join(items))
with
finaluserslist.write("\n".join(items).encode('utf-8'))

Great script, very helpful.

**Comment by packetcat** [comment]
Hi @JeromeSaby 

What Python version are you using?

**Comment by JeromeSaby** [comment]
2.7.6

**Comment by packetcat** [comment]
@JeromeSaby I only support Python 3.x, can you reproduce this issue with Python 3.x?

**Comment by JeromeSaby** [comment]
@staticsafe I can't manage to have python3 working right now. But I'm sure the script works fine in this version.
